version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
 build:
    newman-collection-run-env-timeout:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./collection/Api_Test.postman_collection.json
          environment: ./env/LAMP-staging.postman_environment.json
          timeout: '1000'


